### PR TITLE
Arrow keys support

### PR DESCRIPTION
**Pull request by Arkaeriit**
This PR add the use of arrow keys to move the cursor in normal mode.

This was the feature that prevented me to use your editor in my personal use and I might not be the only one that needs it.
Thank you for your work. This is a really nice project I and think you really managed to make an easy to hack editor.

### CODE REVIEW

**Comment by kyx0r** [comment]
Hey, really cool. I think @clark800 would appreciate something like this, he also wanted arrow keys from insert like in vim, though it probably be a bit more complicated especially with moving up and down. This project is complete (technically today is the deadline). I might reforce push last commit, still need to double check everything cause obviously when making such a call everything should be left in a perfect state (so that no future fixes would ever be necessary). Strive for completion is something that's needed because a few people complain how their custom patches break especially in the last 2 months where 1000s lines of code where changed in one way or another. This can be great, because I can start to make obscure features and distribute them as optional patches.

**Comment by kyx0r** [comment]
I will take a look at your patch, if it may be done more concisely.

**Comment by kyx0r** [comment]
I contemplated this for a while and came to the conclusion that the final version will not include this patch. Whilst I found nothing wrong with the implementation itself, afterall it's not really standard way to use vi. Feature is more like a customization type thing where we just provide a different keybind to do the same thing, but a lot more complex due to the escape seq handling. Well today is the last day to make changes, so I'd rather stay on the safe side and leave this as an optional patch to those who need it.

**Comment by Arkaeriit** [comment]
Understandable. The nice things with free software is that anyone can change it to fulfill their need.
Once again, I want to thank you for the work you did with this nice editor.

**Pull request closed without merging**
