### PR TITLE
Fixed "was already compiled"

### PR DESCRIPTION
**Pull request by polluks**
After a pull the build script now sees new source code.

### CODE REVIEW

**Comment by xplshn** [comment]
There's nothing to fix there. If you run ./cbuild.sh without arguments, it will build ./vi, if you run it again, it'll tell you that there's nothing to do. But if you run `./cbuild.sh build` it will build ./vi again.

**Comment by Un1q32** [comment]
I think it should just compile it again regardless.  Even the find command seems overkill, just always compile again.

**Comment by kyx0r** [comment]
> I think it should just compile it again regardless. Even the find command seems overkill, just always compile again.

I agree. I think the reason the behavior of ./build.sh (without arguments) was changed because this gives a way for xplshn's package build system to not do redundant rebuilds. @xplshn Is this correct?

However, there is another problem that I see, if you do ./cbuild.sh install, will always do rebuild which may not be desirable in some cases.

**Comment by xplshn** [comment]
> @xplshn Is this correct?

Yes, but since `vi.c` is so small, it is not a problem for me, and you should cater the needs of your users, not mine :)

**Comment by Un1q32** [comment]
> However, there is another problem that I see, if you do ./cbuild.sh install, will always do rebuild which may not be desirable in some cases.

maybe use find to make an already_built_check() function that can be used in the build and install functions

**Pull request closed without merging**
