### PR TITLE
Improve `build.sh`

### PR DESCRIPTION
**Pull request by xplshn**
Hi! Awesome project. Great text editor. I wanted to add this to `a-utils`, but I had to add a `cbuild.sh` file that `a-utils/build.sh` could detect, so I spent some time modifying `build.sh` with the following objectives:

1. Pretty and consistent output
2. Error handling
3. Easy to modify
4. Have an excuse to rename build.sh to cbuild.sh and add "retrieve" to it.

I'd be very grateful if this could be merged. Thanks!

### CODE REVIEW

**Comment by Un1q32** [comment]
Hi, I'm the guy who wrote basically all of the current build.sh, I'd like to offer some feedback and ask some questions.

- It looks like you intended to make no arguments do the same thing as build, but that didn't work.  The only way to do that that I'm aware of would be to put a check for `$1` being empty in the `*)` part of the case statement
- why is pgobuild still in a function?  just inline it.
- `clean` failing when vi doesn't exist seems weird, standard practice for build systems seems to be clean only fails if files it tried to delete couldn't be deleted
- a few cases where you call external binaries that should be replaced with shell builtin usage, `basename $foo` should be replaced with `${foo##*/}` and `which foo` should be replaced with `command -v foo`
- I like that optimization flags are separate from CFLAGS, but I think the variable should be renamed to `OPTFLAGS` (I've seen that name used more often then any other, seems like a de-facto standard) and made user configurable, replacing line 52 with `: "${OPTFLAGS:=-O2}"` would do that.
- on line 4, some POSIX shells don't make `$0` a full path to the script so that would break with them.
- line 32, `eval "$*"` is very bad because it does weird splitting on arguments, shellcheck should warn for this IMO, use `"$@"` instead
- line 102, no need to do that default setting again, its already done on line 44
- modifying the build system to be compatible with some other project seems weird, why not just maintain a fork of the repo with those changes

Feel free to ask me anything or explain why anything I've said is wrong.

**Comment by xplshn** [comment]
> It looks like you intended to make no arguments do the same thing as build, but that didn't work. The only way to do that that I'm aware of would be to put a check for $1 being empty in the *) part of the case statement

This works, actually, I forgot to change the `while` loop on the version I pushed, but the case does work. And for shells that don't work with this, there's still "build", so, it shouldn't be a problem. (I tested in: ksh, in OpenBSD didn't yield errors, and `ash` didn't either in Alpine Linux. I haven't checked with other shells/systems)

> why is pgobuild still in a function? just inline it.
Because it is easier to add the log statements that way

> line 32, eval "$*" is very bad because it does weird splitting on arguments, shellcheck should warn for this IMO, use "$@" instead

Shellcheck didn't yield errors because `"$*"` is basically the same as `"$@"`, except that when "$@" is quoted it will respect quotes. however, changing it to a `"$@"` in the case of run() will yield warnings, because using eval negates the benefits of arrays, which are: conserving whitespace, in this case, so the correct thing to do would be to use `$*` or use `sh -c "$@"`, except sh -c will mask exit codes, AFAIK... Using `eval` hasn't been a problem up until now, so I don't see why the need to change it, see: https://stackoverflow.com/questions/2761723/what-is-the-difference-between-and-in-shell-scripts

**Comment by Un1q32** [comment]
> changing it to a `"$@"` in the case of run() will yield warnings, because using eval negates the benefits of arrays

I meant literally having `"$@"` as the whole line, should have made that more clear, also I just realized the old build.sh also does `eval "$*"`, still bad.

> Using eval hasn't been a problem up until now, so I don't see why the need to change it

It's not a problem until it is, trust me, `$*` has been the cause for many hours of very not fun debugging sessions.
It's not exactly the most important change but I feel it's generally better to always use best practices, the shellcheck warn for `eval "$@"` also says to use `"$@"`, not `eval "$*"`

**Comment by xplshn** [comment]
> the shellcheck warn for eval "$@" also says to use "$@", not eval "$*"
2024-07-23-234656_1366x768_scrot

You can't expand/execute `"$@"`, but `$@` does work, so I will change it as requested.

**Comment by xplshn** [comment]
2024-07-23-235758_688x82_scrot

shellcheck's output hasn't changed, so, that's great. I check that `run()` still works. Unless there is some weird edge-case, it should continue to work great. And with this, I think I've taken into account all of your concerns.

Thanks for paying attention to the PR and the `src` :)
I appreciate the effort a lot, thanks!

**Comment by Un1q32** [comment]
> You can't expand/execute `"$@"`, but `$@` does work, so I will change it as requested.

Of all the things I've been certain of before checking, I've never been more certain of anything then `"$@"` being valid, I swear I've used `"$@"` raw multiple times, but you are right.
I tested `$@` and it seems to handle whitespace the same as eval "$*" so I guess it doesn't make a difference.  Sorry for wasting your time.

**Comment by xplshn** [comment]
It happens that "$@" is an array of all arguments, while "$*" is a string of all arguments from "$1" the shell's maximum amount of arguments. Which in my shell is:
```
]@ getconf ARG_MAX
131072
]@
```
In any case, using `$@` does make the shell do less work. So that's what I'll go with, unless I find any issues that don't happen with `eval "$*"`, which is what I've always used.

> Sorry for wasting your time.

Don't worry, I don't feel that way about it

**Comment by Un1q32** [comment]
line 82 should be something like `[ -n "$1" ] && shift`, since running `shift` when no arguments are passed causes errors in most shells, only shell I tested that didn't error was bash, which did nothing in 3.2 (version in macOS) and warned in 5.2 (latest)

**Comment by xplshn** [comment]
> `[ -n "$1" ] && shift`

Nice catch!

**Comment by kyx0r** [comment]
What's the rationale behind renaming the file though? Why can't you just call build.sh from your a-utils build.sh script?

**Comment by xplshn** [comment]
> What's the rationale behind renaming the file though? Why can't you just call build.sh from your a-utils build.sh script?

The idea is to be able to add projects that I need to build to a file named ./extendC.b
The file is a list of repos, I wanted a-utils' build.sh to not build programs that don't ship a `cbuild.sh`, a lot of projects will ship a file named `build.sh` but that doesn't do what `a-utils/build.sh` expects. In any case, I am rewriting `build.sh` in Go, and it'll support a new format where you can specify specific steps to be carried out or specify 'cbuild.sh' as the build command used for the project.

I wanted to avoid complexity, but it is always the same with build systems. It starts simple, and grows into a turing complete scripting language that receives arguments and config files.

**Comment by Un1q32** [comment]
I made a build system once, just a bunch of shell scripts, every package just has it's own script that runs the right commands to build the thing.  There's even a nextvi build script in there, but it bypasses build.sh and instead just runs the compiler directly. https://github.com/Un1q32/iphoneports

**Comment by kyx0r** [comment]
I see, so instead of a package manager you made a build system. Well, in that case I guess it makes sense for relationship to become many to one instead of one to many. So long as cbuild.sh is a valid posix shell script I guess I could care less. Though do let me know in case you happen to rethink your design.

I'll probably merge this change in a day or so, considering the amount of effort you have put into it. Reason being, I have some improvements ideas for tomorrow to put into core nextvi as well. Just more polish on existing feature or two.

**Comment by xplshn** [comment]
> I made a build system once, just a bunch of shell scripts, every package just has it's own script that runs the right commands to build the thing. There's even a nextvi build script in there, but it bypasses build.sh and instead just runs the compiler directly. https://github.com/Un1q32/iphoneports
> 
> Your approach seems like it would be a lot more work for not a lot of benefit, every *nix distro packaging system I'm aware of works pretty much the same as mine, with a custom script for every package.

I like the simplicity of your project. Cool! Why aren't you using sh -c to wrap thing tho?

**Comment by Un1q32** [comment]
BTW the part in the README that mentions the pgobuild should be updated to say cbuild.sh instead of build.sh

**Comment by Un1q32** [comment]
> I like the simplicity of your project. Cool! Why aren't you using sh -c to wrap everything tho?

Where exactly should I be using `sh -c`?

**Comment by xplshn** [comment]
> > I like the simplicity of your project. Cool! Why aren't you using sh -c to wrap everything tho?
> 
> Where exactly should I be using `sh -c`?

In the build scripts, why aren't you wrapping the commands in a big `sh -e -c ""`?

**Comment by Un1q32** [comment]
I maybe should do a `set -e` (been meaning to for like 6 months but haven't gotten around to it) but I don't see where an `sh -c` would be useful.

**Comment by xplshn** [comment]
> I maybe should do a `set -e` (been meaning to for like 6 months but haven't gotten around to it) but I don't see where an `sh -c` would be useful.

I thought that the build scripts were interpreted by a C program. My bad.

**Comment by Un1q32** [comment]
No, it's shell scripts all the way down, well I guess technically they are interpreted by a C program, since the shell is usually written in C.

**Comment by xplshn** [comment]
If the only thing holding this PR back is the rename of cbuild, I can undo that. No problem with that, better than keeping the old ./build.sh.

**Comment by kyx0r** [comment]
Well, if nextvi was something like a mainstream project with packages for every unix system and everything tightly depending on build.sh, then I would probably completely oppose this rename. But considering most users are expected to build the project themselves and customize how they like - consequences of this change are not that great.

**Comment by Un1q32** [comment]
one more nitpick, I think the part at the start that ensures the script doesn't run outside the nextvi directory should be changed to something like this to avoid calling external binaries
```sh
[ "${0%/*}" = "$0" ] && BASE="." || BASE="${0%/*}"
```
`${foo%/*}` is to `dirname` what `${foo##*/}` is to `basename`

**Comment by Un1q32** [comment]
Avoiding calling external binaries in shell scripts has been a bit of an obsession of mine picked up from maintaining pfetch after dylanaraps stopped commiting (same guy who made neofetch)

Read https://github.com/dylanaraps/pure-sh-bible

**Comment by xplshn** [comment]
> [ "${0%/*}" = "$0" ] && BASE="." || BASE="${0%/*}"

Like this I suppose?

```
POSIXLY_CORRECT=1
cbuild_OPWD="$PWD"
[ "${0%/*}" = "$0" ] && BASE="." || BASE="${0%/*}"
if [ "$OPWD" != "$BASE" ]; then
    cd "$BASE" || log "$R" "Unable to change directory to ${BASE##*/}. Re-execute using a POSIX shell and check again."
fi
trap 'cd "$cbuild_OPWD"' EXIT

```

**Comment by xplshn** [comment]
> Avoiding calling external binaries in shell scripts has been a bit of an obsession of mine picked up from maintaining pfetch after dylanaraps stopped commiting (same guy who made neofetch)
> 
> Read https://github.com/dylanaraps/pure-sh-bible

I understand, and I get why :)

**Comment by kyx0r** [comment]
Yes, please indicate when you think this is fully ready for merge. 

> Avoiding calling external binaries in shell scripts has been a bit of an obsession of mine picked up from maintaining pfetch after dylanaraps stopped commiting (same guy who made neofetch)
> 
> Read https://github.com/dylanaraps/pure-sh-bible

Me too. BTW, If you do call external processes under win32 platform, it makes your scripts run insanely slow due to, ughh windows being what it is. And msys doing what it can :/

**Comment by xplshn** [comment]
I think this is ready. Unless you guys find anything that can be improved.

**Comment by Un1q32** [comment]
> > [ "${0%/_}" = "$0" ] && BASE="." || BASE="${0%/_}"
> 
> Like this I suppose?
> 
> ```
> POSIXLY_CORRECT=1
> cbuild_OPWD="$PWD"
> [ "${0%/*}" = "$0" ] && BASE="." || BASE="${0%/*}"
> if [ "$OPWD" != "$BASE" ]; then
>     cd "$BASE" || log "$R" "Unable to change directory to ${BASE##*/}. Re-execute using a POSIX shell and check again."
> fi
> trap 'cd "$cbuild_OPWD"' EXIT
> ```

Yes, and you can remove the comment about rerunning with a POSIX shell as all POSIX shells should handle that fine, unless they don't guarantee `$0` to be a full or relative path to the script, which I think some old ones do, but those instead put the C `argv[0]` in there verbatim, which should still work in all cases except when the script is run from PATH instead of directly, which is only really a problem for scripts like pfetch, not build scripts, but the `cd` will still verify the path in those cases, or to be extra careful you can `[ -f vi.c ]` but I don't think thats needed.

**Comment by xplshn** [comment]
> > [ "${0%/_}" = "$0" ] && BASE="." || BASE="${0%/_}"
> 
> Like this I suppose?
> 
> ```
> POSIXLY_CORRECT=1
> cbuild_OPWD="$PWD"
> [ "${0%/*}" = "$0" ] && BASE="." || BASE="${0%/*}"
> if [ "$OPWD" != "$BASE" ]; then
>     cd "$BASE" || log "$R" "Unable to change directory to ${BASE##*/}. Re-execute using a POSIX shell and check again."
> fi
> trap 'cd "$cbuild_OPWD"' EXIT
> ```

I realized that we need to know the dirname of $BASE for the log() calls. They say: Building Nextvi, but with the line changed to `[ "${0%/*}" = "$0" ] && BASE="." || BASE="${0%/*}"` they say: Building "."

**Comment by Un1q32** [comment]
Why not just hardcode the word nextvi in there?

**Comment by Un1q32** [comment]
> If you do call external processes under win32 platform, it makes your scripts run insanely slow due to, ughh windows being what it is. And msys doing what it can :/

Someday I'll send some patches to neofetch/hyfetch removing as many external process uses as I can, they do it a lot and running on Windows is extremely slow.

**Comment by xplshn** [comment]
> Why not just hardcode the word nextvi in there?

I don't hardcode the word because having BASE be the BASE directory where you build from makes sense, and using the basename of BASE also makes sense for this. Adding a variable named NAME="NextVi" seems kind of pointless when you can just use the syntax you mentioned already: `${foo##*/}`

I'd consider ./cbuild.sh finished at this point. Further changes can be made after merging. But if you notice anything that can be improved, do tell me and I will look into it. Thanks :)

**Comment by Un1q32** [comment]
> > If you do call external processes under win32 platform, it makes your scripts run insanely slow due to, ughh windows being what it is. And msys doing what it can :/
> 
> Someday I'll send some patches to neofetch/hyfetch removing as many external process uses as I can, they do it a lot and running on Windows is extremely slow.

Also if you just want to run POSIX scripts https://frippery.org/busybox/ feels a lot faster then MSYS2 or Cygwin

**Comment by Un1q32** [comment]
lines 83-85 are a bit unreadable, I would recommend changing it to an if else
on line 120, pass the `-f` flag to rm so it won't throw a warning when the file doesn't exist

Also I thought of a solution to replace the use of `realpath`, use `[ "${0%/*}" = "$0" ] && BASE="." || BASE="${0%/*}"` but add `BASE="${PWD%/}"` after the `cd`

**Comment by xplshn** [comment]
image
It seems to be working great :)

**Comment by kyx0r** [comment]
Alright, patch merged. Thanks! I love it xD. If you want to make more changes to it push them up here, I'll cherry pick. Or if this is completed feel free to close out.

**Comment by xplshn** [comment]
Okay, I consider it done then! Thank!

**Comment by kyx0r** [comment]
Good to close. Thanks and great discussion btw!

**Pull request closed without merging**
