### PR TITLE
readonly.patch: use bool instead of int

### PR DESCRIPTION
**Pull request by Un1q32**
save a bit of memory

### CODE REVIEW

**Comment by kyx0r** [comment]
Just use char, you're not saving anything here anyways...

**Comment by kyx0r** [comment]
The more changes in the patch, the more likely it will conflict with other patches. So also think strategically.

**Comment by Un1q32** [comment]
Updated to use char.
By the way, are all members of ex_buf initialized to 0?  If not I should make sure ex_buf->readonly is set to 0 with an else on the `if ((access(arg, F_OK) == 0 && access(arg, W_OK) == -1) || readonly)` line.

**Comment by kyx0r** [comment]
It's not initialized. I think you should do it in bufs_open() or somewhere later on the code.

**Comment by Un1q32** [comment]
Done

**Comment by kyx0r** [comment]
Applied, thanks!

**Pull request closed without merging**
