### PR TITLE
Implement a Makefile

### PR DESCRIPTION
**Pull request by ismaell**

### CODE REVIEW

**Comment by kyx0r** [comment]
Why? No need for make in project like this.

**Comment by kyx0r** [comment]
Portable systems are more likely to have a posix compliant shell installed on their system than make. However if you encountered a problem with current build.sh let me know, I'll see what can be fixed.

**Comment by ismaell** [comment]
Well, I thought it might be interesting. Makefiles are better with integration and packaging procedures for distributions. The provided Makefile works fine with all major variants of Make. It's meant as an alternative.

As for portability, an improvement would be to check the flags that the compiler supports before adding them to `CFLAGS`. It could probably be compiled on non-gcc-like compilers just fine.

BTW, specifying `_BSD_SOURCE` conditionally is probably not a good idea.

**Comment by OldWorldOrdr** [comment]
why isn't -O2 in the cflags? on both this and the build.sh

**Comment by ismaell** [comment]
> why isn't -O2 in the cflags? on both this and the build.sh

From my POV, if it were a sound default, then it would be the compiler's default.

**Comment by OldWorldOrdr** [comment]
@ismaell iirc compiler default is to optimize for compile time, to allow for quick testing.  Code that's intended to be used for anything besides testing should use -O2

**Comment by kyx0r** [comment]
I'm ok with having this on patches branch. Added now.

**Pull request closed without merging**
