### PR TITLE
add ex-scripting.patch

### PR DESCRIPTION
**Pull request by Un1q32**
Run the ex command `:sc <shell command>` and the stdout of that command will be ran as ex commands.

The current version does not export any environment variables.  What info should we export, and what is the best way to get that info?

### CODE REVIEW

**Comment by kyx0r** [comment]
Hi Joey, I will have a look at this tomorrow.

**Comment by kyx0r** [comment]
Sorry, time didn't suffice quite yet, as I was busy fixing and refactoring some core aspects I had in mind. It's really difficult to come up with right words to describe complex behaviors in the manual too. Every word has to be to a 100% precision.
Soon enough I'll get to this as well.

**Comment by kyx0r** [comment]
Joey, base nextvi can already do this kind of script calling. Here is a sample command for you to try:
```:.g//!echo 'se tbs=4'```

Though the only situation when it won't execute is if you open a brand new "unnamed" buffer, but
it can also be circumvented by modifying the command to be:
```:&i|.g//!echo 'se tbs=4'```

Not much is needed in terms of implementation, the only thing to implement is a way export the data to the script, and the format that would be in.

For example, this works too:
```:!export curtbs=111 && echo "se tbs=$curtbs"```
prints 111 as expected. Now, all you do is make an ex function in C which puts the data in the command string like this.

**Comment by kyx0r** [comment]
Although this is a bit of a stretch, since we're going to be modifying C code (instead of a macro), might as well not hook to the global command and make things a bit more performant. The part of :sc command that would call the script should be like 5 lines of code if existing nextvi functions are used properly.

**Comment by Un1q32** [comment]
> Joey, base nextvi can already do this kind of script calling. Here is a sample command for you to try: `:.g//!echo 'se tbs=4'`

https://asciinema.org/a/I5Wg0yAlm4iyllyDsnl5IxB2a am I doing something wrong?

**Comment by Un1q32** [comment]
> Although this is a bit of a stretch, since we're going to be modifying C code (instead of a macro), might as well not hook to the global command and make things a bit more performant. The part of :sc command that would call the script should be like 5 lines of code if existing nextvi functions are used properly.

Do you mean make ex_script a static function, or shrink the ex_script function somehow?  I wanted to reuse the ex_script function from exrc.patch to save size when using both together.

**Comment by kyx0r** [comment]
> > Joey, base nextvi can already do this kind of script calling. Here is a sample command for you to try: `:.g//!echo 'se tbs=4'`
> 
> https://asciinema.org/a/I5Wg0yAlm4iyllyDsnl5IxB2a am I doing something wrong?

Maybe a shell issue? Try this:
```:se noish|.g//!printf 'se tbs=4'```

Tested with bash. If that works, remove se noish and see

**Comment by Un1q32** [comment]
se noish fixed it, removing se noish doesnt work

**Comment by kyx0r** [comment]
> Do you mean make ex_script a static function, or shrink the ex_script function somehow? I wanted to reuse the ex_script function from exrc.patch to save size when using both together.

I mean, the patch doesn't need to reuse ex_script, Nextvi implements it's own version on popen like function. 

You can call:
```
char *cmd_pipe(char *cmd, char *ibuf, int oproc)
```

It gives you more control over stdin and stdout + the ex ish flag.

I'll add the version of this patch that uses it later. And also probably add code that will export the filetype string just as a demo.

**Comment by Un1q32** [comment]
> I'll add the version of this patch that uses it later. And also probably add code that will export the filetype string just as a demo.

We still need to decide what environment variables to export and such, the patch is a lot less useful without that part.

**Comment by kyx0r** [comment]
> se noish fixed it, removing se noish doesnt work

Which shell are you using? I guess it doesn't like the -i flag or does something weird with it.
Run this command in shell:
```
sh -i -c 'echo "se tbs=4"'
```

see if it does anything different. To debug it you can also pass -x if supported at all
```
sh -i -x -c 'echo "se tbs=4"'
```

**Comment by kyx0r** [comment]
> > I'll add the version of this patch that uses it later. And also probably add code that will export the filetype string just as a demo.
> 
> We still need to decide what environment variables to export and such, the patch is a lot less useful without that part.

Will decide as time goes on based on what is useful. I'm thinking exporting filetype and all global variables. Maybe also export the buffer data. Though the latter might be too big for env variable

**Comment by Un1q32** [comment]
> > se noish fixed it, removing se noish doesnt work
> 
> Which shell are you using? I guess it doesn't like the -i flag or does something weird with it. Run this command in shell:
> 
> ```
> sh -i -c 'echo "se tbs=4"'
> ```
> 
> see if it does anything different. To debug it you can also pass -x if supported at all
> 
> ```
> sh -i -x -c 'echo "se tbs=4"'
> ```

I'm using macOS bash 3.2.57, piping output to xxd show stdout is identical with and without -i

**Comment by kyx0r** [comment]
> I'm using macOS bash 3.2.57, piping output to xxd show stdout is identical with and without -i

It could also be that your shell pointer is messed up, like /bin/sh is symlinked to something else or /etc/shells
is wrong. To get to the bottom of it, I would also check the $SHELL env variable and try hard coding the shell in term.c

https://github.com/kyx0r/nextvi/blob/master/term.c#L257

change to this
```
static char *sh[] = {"bash", NULL};
```

**Comment by Un1q32** [comment]
$SHELL = /bin/zsh
/bin/sh is a symlink to /bin/bash

Hardcoding the shell in term.c worked

**Comment by Un1q32** [comment]
Running `zsh -i -c 'echo "se tbs=4"'` also sources .zshrc before running the command.

**Comment by kyx0r** [comment]
> Running `zsh -i -c 'echo "se tbs=4"'` also sources .zshrc before running the command.

Yep, that is what -i flag indented to do. But you will have problems if your .zshrc outputs anything to stdout. The solution is to design your .zshrc to not output anything or output only conditionally. My .rc and .bashrc setup is completely silent to make ish work properly.

**Comment by kyx0r** [comment]
I've disabled the ish by default now. Most likely this is a better default for compatibility sake. Now users will have to discover and set it themselves by reading the manual, despite how insanely overpowered this feature is once your grok it.

**Comment by kyx0r** [comment]
Please see the following implementation of this patch:
https://github.com/kyx0r/nextvi/blob/patches/ex-scripting.patch

If you run ```:sc env``` you should find the FT= variable set to the filetype

**Comment by kyx0r** [comment]
```:sx echo 'se tbs=4'```

:sx  will run the stdout output as ex commands

**Comment by Un1q32** [comment]
I think environment variable names should be prefixed with something like `NEXTVI_` to avoid conflicts.  FT is pretty generic.

Also use of `extern char **environ;` is not portable, won't compile on old versions of macOS.

Also I think the way you're using environ here is unsafe.  Running `setenv()` should realloc environ, which could cause a UAF or use an old version of the environment.

**Comment by Un1q32** [comment]
Just confirmed that at least on macOS 14, the `$FT` environment variable doesn't show up for the script unless you run `:sx` at least twice.

**Comment by kyx0r** [comment]
> I think environment variable names should be prefixed with something like `NEXTVI_` to avoid conflicts. FT is pretty generic.
> 
> Also use of `extern char **environ;` is not portable, won't compile on old versions of macOS.
> 
> Also I think the way you're using environ here is unsafe. Running `setenv()` should realloc environ, which could cause a UAF or use an old version of the environment.

You're right. The point of using environ here is to add new vars to the old version of environment. It's not required and we could just remove environ altogether. Though in that case not every system env var would be available to the script

**Comment by kyx0r** [comment]
> I think environment variable names should be prefixed with something like `NEXTVI_` to avoid conflicts. FT is pretty generic.

I agree.

> Also use of `extern char **environ;` is not portable, won't compile on old versions of macOS.

Hm, not sure if there is a portable way to get all env vars though. A tradeoff is a tradeoff. Hopefully its old enough to be irrelevant.

**Comment by Un1q32** [comment]
There's a workaround for old macOS
```c
#ifdef __APPLE__
#include <crt_externs.h>
#define environ (*_NSGetEnviron())
#else
extern char **environ;
#endif
```

**Comment by kyx0r** [comment]
Thanks, I've implemented this check and more useful variables now. Have a look

**Comment by Un1q32** [comment]
Looks good!

**Comment by kyx0r** [comment]
@Un1q32 Have a look at the latest :wl command. It is capable of hooking into shell return codes now. It might make ex-scripting.patch obsolete or even more powerful in some cases.

Over time, I may make it even more powerful by propagating all vi return codes back to ex. I just don't know how to do this cleanly yet. Keep in mind that just like ex, in outside UNIX environment not every command reports error codes properly, so be careful with potential infinite loops if you try using it with $ arguments.

**Pull request closed without merging**
