### PR TITLE
Differentiated options

### PR DESCRIPTION
**Pull request by polluks**
BTW .txt inhibits syntax highlighting

### CODE REVIEW

**Comment by kyx0r** [comment]
Thank you, Stefan. Patch applied.
If you're talking about the highlight on .txt file, yes nextvi does default .txt to roff syntax highlight.
This is defined in conf.c at https://github.com/kyx0r/nextvi/blob/master/conf.c#L9

**Comment by polluks** [comment]
Fine.
I was talking about github...

**Comment by kyx0r** [comment]
> Fine. I was talking about github...

Would it be better to change it to .roff extension instead? I hope that would work for github. Your thoughts?

**Comment by Un1q32** [comment]
The synopsis section still has `[-esv]` and doesn't include the `-m` option, would make a PR but it's so small plus I noticed it at school so I would have to wait til I get home.

**Comment by polluks** [comment]
> Would it be better to change it to .roff extension instead? I hope that would work for github. Your thoughts?

You could use .gitattributes for mapping, however .1 is the common extension for roff. I don't see the point.

**Comment by kyx0r** [comment]
> > Would it be better to change it to .roff extension instead? I hope that would work for github. Your thoughts?
> 
> You could use .gitattributes for mapping, however .1 is the common extension for roff. I don't see the point.

Fair enough. Will do later.

> The synopsis section still has `[-esv]` and doesn't include the `-m` option, would make a PR but it's so small plus I noticed it at school so I would have to wait til I get home.

True, might be annoying to make a PR for small changes like this. Do you want push access to that branch? In case you plan to actively work on the manual, let me know.

**Comment by Un1q32** [comment]
> Do you want push access to that branch? In case you plan to actively work on the manual, let me know.

I don't have plans to actively work on the manual right now.

**Pull request closed without merging**
